#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate bounded C tables for the pinned Unicode normalization profile."""

from __future__ import annotations

import pathlib
import zipfile


ROOT = pathlib.Path(__file__).resolve().parent
UCD_ARCHIVE = ROOT / "idna-data" / "UCD-17.0.0.zip"
OUTPUT = ROOT / "generated_normalization_data.h"
VERSION = "17.0.0"
MAX_MAPPING_LENGTH = 18
MAX_RECURSIVE_EXPANSION = 18
MAX_DEPTH = 32


def codepoint(value: int) -> str:
    return f"0x{value:04X}u"


def parse_unicode_data(contents: str):
    decompositions = []
    combining_classes = []
    for line in contents.splitlines():
        fields = line.split(";")
        cp = int(fields[0], 16)
        combining_class = int(fields[3])
        mapping = fields[5].split()
        if combining_class:
            combining_classes.append((cp, combining_class))
        if mapping:
            compatibility = mapping[0].startswith("<")
            if compatibility:
                mapping = mapping[1:]
            values = [int(value, 16) for value in mapping]
            if not values or len(values) > MAX_MAPPING_LENGTH:
                raise SystemExit(f"unsupported decomposition length for U+{cp:04X}")
            decompositions.append((cp, compatibility, values))
    return decompositions, combining_classes


def parse_composition_exclusions(contents: str) -> set[int]:
    if not contents.splitlines()[0].startswith(
        f"# DerivedNormalizationProps-{VERSION}.txt"
    ):
        raise SystemExit("DerivedNormalizationProps Unicode version mismatch")
    exclusions: set[int] = set()
    for line in contents.splitlines():
        data = line.split("#", 1)[0].strip()
        if not data:
            continue
        value, property_name = (part.strip() for part in data.split(";", 1))
        if property_name != "Full_Composition_Exclusion":
            continue
        if ".." in value:
            first, last = (int(part, 16) for part in value.split("..", 1))
        else:
            first = last = int(value, 16)
        exclusions.update(range(first, last + 1))
    return exclusions


def validate_expansion(decompositions) -> int:
    lookup = {cp: (compatibility, values)
              for cp, compatibility, values in decompositions}
    maximum = 0

    def expand(cp: int, compatibility: bool, depth: int) -> int:
        if depth > MAX_DEPTH:
            raise SystemExit("normalization decomposition recursion exceeds bound")
        if 0xAC00 <= cp < 0xAC00 + 11172:
            return 2 + int((cp - 0xAC00) % 28 != 0)
        row = lookup.get(cp)
        if row is None or (row[0] and not compatibility):
            return 1
        return sum(expand(value, compatibility, depth + 1)
                   for value in row[1])

    for cp, _, _ in decompositions:
        maximum = max(maximum, expand(cp, False, 0), expand(cp, True, 0))
    if maximum > MAX_RECURSIVE_EXPANSION:
        raise SystemExit(
            f"recursive decomposition requires {maximum} slots; "
            f"runtime bound is {MAX_RECURSIVE_EXPANSION}"
        )
    return maximum


def main() -> None:
    if not UCD_ARCHIVE.is_file():
        raise SystemExit(f"missing pinned Unicode archive: {UCD_ARCHIVE}")
    with zipfile.ZipFile(UCD_ARCHIVE) as archive:
        unicode_data = archive.read("UnicodeData.txt").decode("utf-8")
        normalization_data = archive.read(
            "DerivedNormalizationProps.txt"
        ).decode("utf-8")
    if not unicode_data.startswith("0000;"):
        raise SystemExit("UnicodeData is malformed or out of order")
    decompositions, combining_classes = parse_unicode_data(unicode_data)
    exclusions = parse_composition_exclusions(normalization_data)
    maximum_expansion = validate_expansion(decompositions)

    mapping_values: list[int] = []
    decomposition_rows: list[str] = []
    compositions: list[tuple[int, int, int]] = []
    for cp, compatibility, values in decompositions:
        offset = len(mapping_values)
        mapping_values.extend(values)
        decomposition_rows.append(
            f"    {{ {codepoint(cp)}, {offset}u, {len(values)}u, "
            f"{1 if compatibility else 0}u }},"
        )
        if not compatibility and len(values) == 2 and cp not in exclusions:
            compositions.append((values[0], values[1], cp))
    compositions.sort()

    lines = [
        "/* SPDX-License-Identifier: Unicode-3.0 */",
        "/* Generated by generate_normalization_data.py. Do not edit. */",
        f"/* Unicode normalization database version: {VERSION}. */",
        "#ifndef RIN_UNICODE_GENERATED_NORMALIZATION_DATA_H",
        "#define RIN_UNICODE_GENERATED_NORMALIZATION_DATA_H",
        "",
        f'#define RIN_UNICODE_NORMALIZATION_DATABASE_VERSION "{VERSION}"',
        f"#define RIN_UNICODE_NORMALIZATION_MAX_EXPANSION {maximum_expansion}u",
        "",
        "static const RinUnicodeNormalizationDecompositionEntry",
        "    g_rin_unicode_normalization_decompositions[] = {",
        *decomposition_rows,
        "};",
        "static const size_t g_rin_unicode_normalization_decomposition_count =",
        "    sizeof(g_rin_unicode_normalization_decompositions) /",
        "    sizeof(g_rin_unicode_normalization_decompositions[0]);",
        "",
        "static const uint32_t g_rin_unicode_normalization_mappings[] = {",
    ]
    lines.extend(f"    {codepoint(value)}," for value in mapping_values)
    lines.extend([
        "};",
        "",
        "static const RinUnicodeCombiningClassEntry",
        "    g_rin_unicode_normalization_combining_classes[] = {",
    ])
    lines.extend(
        f"    {{ {codepoint(cp)}, {value}u }},"
        for cp, value in combining_classes
    )
    lines.extend([
        "};",
        "static const size_t g_rin_unicode_normalization_combining_class_count =",
        "    sizeof(g_rin_unicode_normalization_combining_classes) /",
        "    sizeof(g_rin_unicode_normalization_combining_classes[0]);",
        "",
        "static const RinUnicodeCompositionEntry",
        "    g_rin_unicode_normalization_compositions[] = {",
    ])
    lines.extend(
        f"    {{ {codepoint(first)}, {codepoint(second)}, {codepoint(composed)} }},"
        for first, second, composed in compositions
    )
    lines.extend([
        "};",
        "static const size_t g_rin_unicode_normalization_composition_count =",
        "    sizeof(g_rin_unicode_normalization_compositions) /",
        "    sizeof(g_rin_unicode_normalization_compositions[0]);",
        "",
        "#endif",
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(
        f"wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes): "
        f"{len(decompositions)} decompositions, "
        f"{len(combining_classes)} combining classes, "
        f"{len(compositions)} compositions, max expansion {maximum_expansion}"
    )


if __name__ == "__main__":
    main()
