/* SPDX-License-Identifier: MIT */
/* Generated by scripts/generate_rinicu_data.py. */
#ifndef RIN_UNICODE_GENERATED_LOCALE_CATALOG_H
#define RIN_UNICODE_GENERATED_LOCALE_CATALOG_H

typedef struct RinUnicodeGeneratedLocale {
    const char* name;
    const char* locale_id;
    const char* language;
    const char* territory;
    const char* script;
    const char* codeset;
    rin_unicode_lconv_t lconv;
} RinUnicodeGeneratedLocale;

static RinUnicodeGeneratedLocale const g_rin_unicode_generated_locales[] = {
    {
        "C",
        "root",
        "",
        "",
        "",
        "ASCII",
        {
            ".", "", "", "", "",
            ".", "", "", "", "-",
            127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127
        }
    },
    {
        "en_US.UTF-8",
        "en-US",
        "en",
        "US",
        "Latn",
        "UTF-8",
        {
            ".", ",", "\x03", "USD ", "$",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "en_GB.UTF-8",
        "en-GB",
        "en",
        "GB",
        "Latn",
        "UTF-8",
        {
            ".", ",", "\x03", "GBP ", "\xC2\xA3",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "en_IN.UTF-8",
        "en-IN",
        "en",
        "IN",
        "Latn",
        "UTF-8",
        {
            ".", ",", "\x03", "INR ", "\xE2\x82\xB9",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "es_US.UTF-8",
        "es-US",
        "es",
        "US",
        "Latn",
        "UTF-8",
        {
            ".", ",", "\x03", "USD ", "$",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "de_AT.UTF-8",
        "de-AT",
        "de",
        "AT",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", ".", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "fr_BE.UTF-8",
        "fr-BE",
        "fr",
        "BE",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", ".", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "ja_JP.UTF-8",
        "ja-JP",
        "ja",
        "JP",
        "Jpan",
        "UTF-8",
        {
            ".", ",", "\x03", "JPY ", "\xC2\xA5",
            ".", ",", "\x03", "", "-",
            0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "zh_CN.UTF-8",
        "zh-CN",
        "zh",
        "CN",
        "Hans",
        "UTF-8",
        {
            ".", ",", "\x03", "CNY ", "\xC2\xA5",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "zh_TW.UTF-8",
        "zh-TW",
        "zh",
        "TW",
        "Hant",
        "UTF-8",
        {
            ".", ",", "\x03", "TWD ", "NT$",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "ko_KR.UTF-8",
        "ko-KR",
        "ko",
        "KR",
        "Kore",
        "UTF-8",
        {
            ".", ",", "\x03", "KRW ", "\xE2\x82\xA9",
            ".", ",", "\x03", "", "-",
            0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "fr_FR.UTF-8",
        "fr-FR",
        "fr",
        "FR",
        "Latn",
        "UTF-8",
        {
            ",", " ", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", " ", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "de_DE.UTF-8",
        "de-DE",
        "de",
        "DE",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", ".", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "es_ES.UTF-8",
        "es-ES",
        "es",
        "ES",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", ".", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "es_MX.UTF-8",
        "es-MX",
        "es",
        "MX",
        "Latn",
        "UTF-8",
        {
            ".", ",", "\x03", "MXN ", "MX$",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "it_IT.UTF-8",
        "it-IT",
        "it",
        "IT",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", ".", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "pt_BR.UTF-8",
        "pt-BR",
        "pt",
        "BR",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "BRL ", "R$",
            ",", ".", "\x03", "", "-",
            2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
        }
    },
    {
        "pt_PT.UTF-8",
        "pt-PT",
        "pt",
        "PT",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", ".", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "ru_RU.UTF-8",
        "ru-RU",
        "ru",
        "RU",
        "Cyrl",
        "UTF-8",
        {
            ",", " ", "\x03", "RUB ", "\xE2\x82\xBD",
            ",", " ", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "uk_UA.UTF-8",
        "uk-UA",
        "uk",
        "UA",
        "Cyrl",
        "UTF-8",
        {
            ",", " ", "\x03", "UAH ", "\xE2\x82\xB4",
            ",", " ", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "tr_TR.UTF-8",
        "tr-TR",
        "tr",
        "TR",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "TRY ", "\xE2\x82\xBA",
            ",", ".", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "pl_PL.UTF-8",
        "pl-PL",
        "pl",
        "PL",
        "Latn",
        "UTF-8",
        {
            ",", " ", "\x03", "PLN ", "z\xC5\x82",
            ",", " ", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "nl_NL.UTF-8",
        "nl-NL",
        "nl",
        "NL",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", ".", "\x03", "", "-",
            2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
        }
    },
    {
        "sv_SE.UTF-8",
        "sv-SE",
        "sv",
        "SE",
        "Latn",
        "UTF-8",
        {
            ",", " ", "\x03", "SEK ", "kr",
            ",", " ", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "fi_FI.UTF-8",
        "fi-FI",
        "fi",
        "FI",
        "Latn",
        "UTF-8",
        {
            ",", " ", "\x03", "EUR ", "\xE2\x82\xAC",
            ",", " ", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "da_DK.UTF-8",
        "da-DK",
        "da",
        "DK",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "DKK ", "kr",
            ",", ".", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "cs_CZ.UTF-8",
        "cs-CZ",
        "cs",
        "CZ",
        "Latn",
        "UTF-8",
        {
            ",", " ", "\x03", "CZK ", "K\xC4\x8D",
            ",", " ", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "hu_HU.UTF-8",
        "hu-HU",
        "hu",
        "HU",
        "Latn",
        "UTF-8",
        {
            ",", " ", "\x03", "HUF ", "Ft",
            ",", " ", "\x03", "", "-",
            0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "ro_RO.UTF-8",
        "ro-RO",
        "ro",
        "RO",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "RON ", "lei",
            ",", ".", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "ar_SA.UTF-8",
        "ar-SA",
        "ar",
        "SA",
        "Arab",
        "UTF-8",
        {
            ".", ",", "\x03", "SAR ", "\xD8\xB1.\xD8\xB3",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
        }
    },
    {
        "fa_IR.UTF-8",
        "fa-IR",
        "fa",
        "IR",
        "Arab",
        "UTF-8",
        {
            "\xD9\xAB", "\xD9\xAC", "\x03", "IRR ", "\xD8\xB1\xDB\x8C\xD8\xA7\xD9\x84",
            "\xD9\xAB", "\xD9\xAC", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "he_IL.UTF-8",
        "he-IL",
        "he",
        "IL",
        "Hebr",
        "UTF-8",
        {
            ".", ",", "\x03", "ILS ", "\xE2\x82\xAA",
            ".", ",", "\x03", "", "-",
            2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
    {
        "hi_IN.UTF-8",
        "hi-IN",
        "hi",
        "IN",
        "Deva",
        "UTF-8",
        {
            ".", ",", "\x03", "INR ", "\xE2\x82\xB9",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "th_TH.UTF-8",
        "th-TH",
        "th",
        "TH",
        "Thai",
        "UTF-8",
        {
            ".", ",", "\x03", "THB ", "\xE0\xB8\xBF",
            ".", ",", "\x03", "", "-",
            2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1
        }
    },
    {
        "id_ID.UTF-8",
        "id-ID",
        "id",
        "ID",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "IDR ", "Rp",
            ",", ".", "\x03", "", "-",
            2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
        }
    },
    {
        "vi_VN.UTF-8",
        "vi-VN",
        "vi",
        "VN",
        "Latn",
        "UTF-8",
        {
            ",", ".", "\x03", "VND ", "\xE2\x82\xAB",
            ",", ".", "\x03", "", "-",
            0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1
        }
    },
};

static size_t const g_rin_unicode_generated_locale_count =
    sizeof(g_rin_unicode_generated_locales) / sizeof(g_rin_unicode_generated_locales[0]);

#endif
